### ISSUE TITLE
OrderedDict(('ra', self.ra), ('dec', self.dec)) in astromodels/core/sky_direction

### ISSUE THREAD

**Issue by henrikef** [giacomov/astromodels#38]
I'm trying to get Fermi-LAT analysis working with 3ML. When I run the test script from the 3ML repository (3ML/threeML/test/test_FermipyLike.py), it fails at the fit() command. The error messages boil down to a problem with the "OrderedDict"s in astromodels/core/sky_direction, see the last lines of the error messages below.

Shouldn't it be

    return collections.OrderedDict([('l', self.l), ('b', self.b)])

and

    return collections.OrderedDict([('ra', self.ra), ('dec', self.dec)])

in lines 225 and 229 in astromodels/core/sky_direction.py? With the square brackets? 

----

```
/home/henrikef/3ML_env/local/lib/python2.7/site-packages/astromodels/core/sky_direction.pyc in parameters(self)
    227         else:
    228 
--> 229             return collections.OrderedDict(('ra', self.ra), ('dec', self.dec))
    230 
    231     @property

/usr/lib/python2.7/collections.pyc in __init__(self, *args, **kwds)
     43         '''
     44         if len(args) > 1:
---> 45             raise TypeError('expected at most 1 arguments, got %d' % len(args))
     46         try:
     47             self.__root

TypeError: expected at most 1 arguments, got 2
```

**Comment by giacomov** [comment]
@henrikef I had fixed this already, but didn't commit it because I was testing it with other things. I have now committed my change to this file, so it should solve your problem.

Thanks for reporting it!

**Comment by henrikef** [comment]
Thanks!

However, after updating, I now get a segmentation fault when I try to import astromodels or threeML. I even set up a fresh install but still no luck. Any ideas?


```
(3ML_20170320_env) henrikef@emanuele-pc:~$ python
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from astromodels import *
Segmentation fault (core dumped)
```

**Comment by giacomov** [comment]
ok, that is weird.

What is your operating system/architecture?

If you have the gdb debugger installed, please run the following:

```
> gdb python
(gdb) run
>>> from astromodels import *
```

and post here the trace after you get the segfault. It should help me understand what is happening, since I cannot reproduce your issue on my system.
